#
#Created by Luis Madrid
#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    May 31, 2021 08:48:00 PM CDT  platform: Darwin

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import gui_ds_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    gui_ds_support.set_Tk_var()
    top = mainWindow (root)
    gui_ds_support.init(root, top)
    root.mainloop()

w = None
def create_mainWindow(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_mainWindow(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    gui_ds_support.set_Tk_var()
    top = mainWindow (w)
    gui_ds_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_mainWindow():
    global w
    w.destroy()
    w = None

class mainWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("564x450+415+174")
        top.minsize(72, 15)
        top.maxsize(1680, 941)
        top.resizable(1,  1)
        top.title("Downselect Tool")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.textDisplay = ScrolledText(top)
        self.textDisplay.place(relx=0.034, rely=0.111, relheight=0.809
                , relwidth=0.303)
        self.textDisplay.configure(background="white")
        self.textDisplay.configure(font="TkTextFont")
        self.textDisplay.configure(foreground="black")
        self.textDisplay.configure(highlightbackground="#d9d9d9")
        self.textDisplay.configure(highlightcolor="black")
        self.textDisplay.configure(insertbackground="black")
        self.textDisplay.configure(insertborderwidth="3")
        self.textDisplay.configure(selectbackground="blue")
        self.textDisplay.configure(selectforeground="white")
        self.textDisplay.configure(wrap="none")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.034, rely=0.044, height=24, width=162)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(font="-family {Helvetica} -size 13")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Files''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.39, rely=0.178, height=24, width=191)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(font="-family {Helvetica} -size 13")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Column of Interest:''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.39, rely=0.333, height=24, width=191)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(font="-family {Helvetica} -size 13")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Files of Interest:''')

        self.btn_of = tk.Button(top)
        self.btn_of.place(relx=0.39, rely=0.4, height=22, width=49)
        self.btn_of.configure(activebackground="#ececec")
        self.btn_of.configure(activeforeground="#000000")
        self.btn_of.configure(background="#d9d9d9")
        self.btn_of.configure(foreground="#000000")
        self.btn_of.configure(highlightbackground="#d9d9d9")
        self.btn_of.configure(highlightcolor="black")
        self.btn_of.configure(relief="raised")
        self.btn_of.configure(text='''Open''', command = gui_ds_support.btn_openfile)

        self.btn_clear = tk.Button(top)
        self.btn_clear.place(relx=0.514, rely=0.4, height=22, width=49)
        self.btn_clear.configure(activebackground="#ececec")
        self.btn_clear.configure(activeforeground="#000000")
        self.btn_clear.configure(background="#d9d9d9")
        self.btn_clear.configure(foreground="#000000")
        self.btn_clear.configure(highlightbackground="#d9d9d9")
        self.btn_clear.configure(highlightcolor="black")
        self.btn_clear.configure(relief="raised")
        self.btn_clear.configure(text='''Clear''', command = gui_ds_support.btn_rest)

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.TProgressbar1 = ttk.Progressbar(top, mode = 'determinate')
        self.TProgressbar1.place(relx=0.151, rely=0.933, relwidth=0.167
                , relheight=0.0, height=16)

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.034, rely=0.933, height=24, width=68)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(font="-family {Helvetica} -size 13")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Progress:''')

        self.btn = tk.Button(top)
        self.btn.place(relx=0.532, rely=0.911, height=22, width=49)
        self.btn.configure(activebackground="#ececec")
        self.btn.configure(activeforeground="#000000")
        self.btn.configure(background="#d9d9d9")
        self.btn.configure(foreground="#000000")
        self.btn.configure(highlightbackground="#d9d9d9")
        self.btn.configure(highlightcolor="black")
        self.btn.configure(relief="raised")
        self.btn.configure(text='''Run''', command = gui_ds_support.run_btn)

        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(relx=0.367, rely=0.022,  relheight=0.956)
        self.TSeparator1.configure(orient="vertical")

        self.Label5 = tk.Label(top)
        self.Label5.place(relx=0.833, rely=0.933, height=24, width=87)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(font="-family {Helvetica} -size 11 -slant italic")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Version 1.0.0''')

        self.TSeparator2 = ttk.Separator(top)
        self.TSeparator2.place(relx=0.762, rely=0.022,  relheight=0.956)
        self.TSeparator2.configure(orient="vertical")

        self.Scrolledtext1 = ScrolledText(top)
        self.Scrolledtext1.place(relx=0.798, rely=0.111, relheight=0.809
                , relwidth=0.199)
        self.Scrolledtext1.configure(background="white")
        self.Scrolledtext1.configure(font="TkTextFont")
        self.Scrolledtext1.configure(foreground="black")
        self.Scrolledtext1.configure(highlightbackground="#d9d9d9")
        self.Scrolledtext1.configure(highlightcolor="black")
        self.Scrolledtext1.configure(insertbackground="black")
        self.Scrolledtext1.configure(insertborderwidth="3")
        self.Scrolledtext1.configure(selectbackground="blue")
        self.Scrolledtext1.configure(selectforeground="white")
        self.Scrolledtext1.configure(wrap="none")

        self.Label6 = tk.Label(top)
        self.Label6.place(relx=0.798, rely=0.044, height=24, width=103)
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(font="-family {Helvetica} -size 13")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''Elements''')

        self.TCombobox2 = ttk.Combobox(top)
        self.TCombobox2.place(relx=0.39, rely=0.244, relheight=0.06, relwidth=0.365)
        #self.TCombobox2.configure(textvariable=gui_ds_support.combobox)
        self.TCombobox2.configure(takefocus="")

        self.Label7 = tk.Label(top)
        self.Label7.place(relx=0.39, rely=0.489, height=24, width=183)
        self.Label7.configure(anchor='w')
        self.Label7.configure(font="-family {Helvetica} -size 13")
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''Find:''')

        self.TSeparator3 = ttk.Separator(top)
        self.TSeparator3.place(relx=0.372, rely=0.178,  relwidth=0.39)

        self.TSeparator4 = ttk.Separator(top)
        self.TSeparator4.place(relx=0.372, rely=0.022,  relwidth=0.39)

        self.TSeparator5 = ttk.Separator(top)
        self.TSeparator5.place(relx=0.372, rely=0.333,  relwidth=0.39)

        self.TCombobox1 = ttk.Combobox(top)
        self.TCombobox1.place(relx=0.39, rely=0.533, relheight=0.06
                , relwidth=0.365)
        self.TCombobox1.configure(textvariable=gui_ds_support.combobox)
        self.TCombobox1.configure(takefocus="")

        self.TSeparator6 = ttk.Separator(top)
        self.TSeparator6.place(relx=0.372, rely=0.489,  relwidth=0.39)

        self.Label8 = tk.Label(top)
        self.Label8.place(relx=0.39, rely=0.044, height=24, width=203)
        self.Label8.configure(anchor='w')
        self.Label8.configure(background="#d9d9d9")
        self.Label8.configure(font="-family {Helvetica} -size 13")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(text='''Select Element Column''')

        self.TCombobox3 = ttk.Combobox(top)
        self.TCombobox3.place(relx=0.39, rely=0.089, relheight=0.06
                , relwidth=0.365)
        #self.TCombobox3.configure(textvariable=gui_ds_support.combobox)
        #self.TCombobox3.configure(takefocus="")

        self.Scrolledtext2 = ScrolledText(top)
        self.Scrolledtext2.place(relx=0.39, rely=0.622, relheight=0.253
                , relwidth=0.358)
        self.Scrolledtext2.configure(background="white")
        self.Scrolledtext2.configure(font="TkTextFont")
        self.Scrolledtext2.configure(foreground="black")
        self.Scrolledtext2.configure(highlightbackground="#d9d9d9")
        self.Scrolledtext2.configure(highlightcolor="black")
        self.Scrolledtext2.configure(insertbackground="black")
        self.Scrolledtext2.configure(insertborderwidth="3")
        self.Scrolledtext2.configure(selectbackground="blue")
        self.Scrolledtext2.configure(selectforeground="white")
        self.Scrolledtext2.configure(wrap='word')


# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, tk.Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()
